# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: cgialus/alus-ci:latest

clone:
  lfs: true

pipelines:
  pull-requests:
    '**': # This runs as default for any branch not elsewhere defined
      - step: # Setup
          script:
            - cd ~
            - mkdir .aws
            - cd .aws
            - echo "[profile sid_man]" > config
            - echo "aws_access_key_id = $SID_MAN_ACCESS_KEY_ID" >> config
            - echo "aws_secret_access_key = $SID_MAN_SECRET_ACCESS_KEY" >> config
            - echo "region = eu-central-1" >> config
            - echo "output = json" >> config
            - cd $BITBUCKET_CLONE_DIR
            - mkdir -p $BITBUCKET_CLONE_DIR/build/test-reports
            - git ls-files --cached --recurse-submodules | tar Tczf - archive.tar.gz
            - $BITBUCKET_CLONE_DIR/build-automation/run_ci_on_ec2_instance.sh "archive.tar.gz" $G3_4xLARGE_INSTANCE_ID "sid_man"
            - date_stamp=$(date +"%Y_%m_%d_%H%M")
            - cd $BITBUCKET_CLONE_DIR/build/ci-artifacts/
            - >
              for file in *; do
                  [ -f "$file" ] && $BITBUCKET_CLONE_DIR/build-automation/put_to_alus_ci_artifacts.sh "${BITBUCKET_BUILD_NUMBER}_${BITBUCKET_BRANCH}_${date_stamp}" $file sid_man
              done 
