#include "terrain_correction_metadata.cuh"

#include "cuda_util.cuh"

alus::terraincorrection::RangeDopplerKernelMetadata alus::terraincorrection::GetKernelMetadata(
    const alus::terraincorrection::RangeDopplerTerrainMetadata& cpu_metadata) {
    alus::cudautil::KernelArray<alus::snapengine::OrbitStateVector> kernel_vectors{
        nullptr, cpu_metadata.orbit_state_vectors.size()};
    auto const orbit_state_vectors_total_size{sizeof(alus::snapengine::OrbitStateVector) *
                                              cpu_metadata.orbit_state_vectors.size()};
    CHECK_CUDA_ERR(cudaMalloc(&kernel_vectors.array, orbit_state_vectors_total_size));
    CHECK_CUDA_ERR(cudaMemcpy(kernel_vectors.array,
                              cpu_metadata.orbit_state_vectors.data(),
                              orbit_state_vectors_total_size,
                              cudaMemcpyHostToDevice));

    alus::terraincorrection::RangeDopplerKernelMetadata d_metadata{cpu_metadata.product_type,
                                                                   cpu_metadata.acquisition_mode,
                                                                   cpu_metadata.antenna_pointing,
                                                                   cpu_metadata.swath,
                                                                   cpu_metadata.proc_time,
                                                                   cpu_metadata.orbit_cycle,
                                                                   cpu_metadata.rel_orbit,
                                                                   cpu_metadata.abs_orbit,
                                                                   cpu_metadata.state_vector_time,
                                                                   cpu_metadata.incidence_near,
                                                                   cpu_metadata.incidence_far,
                                                                   cpu_metadata.slice_num,
                                                                   cpu_metadata.data_take_id,
                                                                   cpu_metadata.first_line_time,
                                                                   cpu_metadata.last_line_time,
                                                                   cpu_metadata.first_near_lat,
                                                                   cpu_metadata.first_near_long,
                                                                   cpu_metadata.first_far_lat,
                                                                   cpu_metadata.first_far_long,
                                                                   cpu_metadata.last_near_lat,
                                                                   cpu_metadata.last_near_long,
                                                                   cpu_metadata.last_far_lat,
                                                                   cpu_metadata.last_far_long,
                                                                   cpu_metadata.pass,
                                                                   cpu_metadata.sample_type,
                                                                   cpu_metadata.mds1_tx_rx_polar,
                                                                   cpu_metadata.mds2_tx_rx_polar,
                                                                   cpu_metadata.mds3_tx_rx_polar,
                                                                   cpu_metadata.mds4_tx_rx_polar,
                                                                   cpu_metadata.algorithm,
                                                                   cpu_metadata.azimuth_looks,
                                                                   cpu_metadata.range_looks,
                                                                   cpu_metadata.range_spacing,
                                                                   cpu_metadata.azimuth_spacing,
                                                                   cpu_metadata.pulse_repetition_frequency,
                                                                   cpu_metadata.radar_frequency,
                                                                   cpu_metadata.line_time_interval,
                                                                   cpu_metadata.total_size,
                                                                   cpu_metadata.num_output_lines,
                                                                   cpu_metadata.num_samples_per_line,
                                                                   cpu_metadata.subset_offset_x,
                                                                   cpu_metadata.subset_offset_y,
                                                                   cpu_metadata.srgr_flag,
                                                                   cpu_metadata.avg_scene_height,
                                                                   cpu_metadata.is_terrain_corrected,
                                                                   cpu_metadata.lat_pixel_res,
                                                                   cpu_metadata.long_pixel_res,
                                                                   cpu_metadata.slant_range_to_first_pixel,
                                                                   cpu_metadata.ant_elev_corr_flag,
                                                                   cpu_metadata.range_spread_comp_flag,
                                                                   cpu_metadata.replica_power_corr_flag,
                                                                   cpu_metadata.abs_calibration_flag,
                                                                   cpu_metadata.calibration_factor,
                                                                   cpu_metadata.chirp_power,
                                                                   cpu_metadata.inc_angle_comp_flag,
                                                                   cpu_metadata.ref_inc_angle,
                                                                   cpu_metadata.ref_slant_range,
                                                                   cpu_metadata.ref_slant_range_exp,
                                                                   cpu_metadata.rescaling_factor,
                                                                   cpu_metadata.bistatic_correction_applied,
                                                                   cpu_metadata.range_sampling_rate,
                                                                   cpu_metadata.range_bandwidth,
                                                                   cpu_metadata.azimuth_bandwidth,
                                                                   cpu_metadata.multilook_flag,
                                                                   cpu_metadata.coregistered_stack,
                                                                   cpu_metadata.centre_lat,
                                                                   cpu_metadata.centre_lon,
                                                                   cpu_metadata.centre_heading,
                                                                   cpu_metadata.centre_heading_2,
                                                                   cpu_metadata.first_valid_pixel,
                                                                   cpu_metadata.last_valid_pixel,
                                                                   cpu_metadata.slr_time_to_first_valid_pixel,
                                                                   cpu_metadata.slr_time_to_last_valid_pixel,
                                                                   cpu_metadata.first_valid_line_time,
                                                                   cpu_metadata.last_valid_line_time,
                                                                   kernel_vectors};
    return d_metadata;
}