# This is a basic workflow to help you get started with Actions

name: CI on AWS GPU instance

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "actions" ]
  pull_request:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start-gpu-instance:
    name: Start GPU Instance
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ESATEST_INTERNALTESTACCOUNT_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ESATEST_INTERNALTESTACCOUNT_ACCESS_KEY }}
        aws-session-token: ${{ secrets.ESATEST_INTERNALTESTACCOUNT_SESSION_TOKEN }}
        aws-region: eu-central-1
    - name: Invoke AWS CLI
      run: |
        aws s3api list-buckets

  run-ci-process:
    name: Build and run unit and integration tests
    runs-on: ubuntu-latest
    needs: start-gpu-instance

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "Hello, world!"
          pwd
          ls -la

      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
#          build-automation/run_ci_on_ec2_instance.sh
