name: End-to-end tests on AWS GPU isntance

on:
  push:
    branches: [ "actions" ]
    max-concurrency: 1
  pull_request:
    branches: [ "development" ]
    max-concurrency: 1
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
    max-concurrency: 1

env:
  RELEASE_PACKAGE_NAME: alus_release_${{github.run_number}}

jobs:
  release-package:
    name: Build package
    runs-on: ubuntu-20.04
    outputs:
      package_filename: ${{ steps.prepare-and-archive.outputs.package_filename }}
    steps:
      - name: Prepare current runner
        run: |
          apt update
          apt install wget
          wget https://raw.githubusercontent.com/cgi-estonia-space/ALUs-platform/main/ubuntu/20_04/focal/install_nvidia_base.sh
          wget https://raw.githubusercontent.com/cgi-estonia-space/ALUs-platform/main/ubuntu/20_04/focal/setup_runtime.sh
          wget https://raw.githubusercontent.com/cgi-estonia-space/ALUs-platform/main/ubuntu/20_04/focal/setup_dev.sh
          chmod +x install_nvidia_base.sh setup_runtime.sh setup_dev.sh
          DEBIAN_FRONTEND=noninteractive ./install_nvidia_base.sh
          nvcc --version
          ./setup_runtime.sh
          ./setup_dev.sh
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build and pack
        env:
          RELEASE_PACKAGE_FILENAME: ${{ env.RELEASE_PACKAGE_NAME }}.tar.gz
          RELEASE_PACKAGE_FILENAME_PATH: /tmp/${{ env.RELEASE_PACKAGE_NAME }}.tar.gz
        run: |
          echo $GITHUB_REF >> $GITHUB_WORKSPACE/VERSION
          $GITHUB_WORKSPACE/build-automation/create_release_package.sh $GITHUB_WORKSPACE $RELEASE_PACKAGE_FILENAME_PATH
          echo "package_path=$RELEASE_PACKAGE_FILENAME_PATH" >> $GITHUB_ENV
          echo "package_filename=$RELEASE_PACKAGE_FILENAME" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.RELEASE_PACKAGE_NAME }}
          path: ${{ env.package_path }}
          retention-days: 3

